Repository AY2223S2-CS2103-W17-4/tp, pull requests merged in 2023-03, with the labels that each got.

#8 Update AboutUs: kimberlybp
  docs/AboutUs.md
  docs/images/kimberlybp.png
  docs/team/kimberlybp.md
Labels: type.Documentation

#32 Initial User Guide Update
  .gitignore
  docs/UserGuide.md
Labels: type.Documentation, type.UserGuide

#33 Update website docs and product site configs
  README.md
  docs/AboutUs.md
  docs/_config.yml
  docs/images/9fc70c892.png
  docs/index.md
Labels: type.Documentation

#34 Update NFRs, codecov readme, dg use cases, value proposition, target user profile
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.DeveloperGuide, type.Documentation

#3 Add utility classes
  src/main/java/seedu/address/commons/util/Pair.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/commons/util/monad/Either.java
  src/main/java/seedu/address/commons/util/monad/parsec/Parser.java
  src/main/java/seedu/address/commons/util/monad/parsec/Result.java
Labels: type.Enhancement

#43 Add commands and ShopModel
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/AddPartCommand.java
  src/main/java/seedu/address/logic/commands/AddServiceCommand.java
  src/main/java/seedu/address/logic/commands/AddVehicleCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entity/shop/Shop.java
  src/main/java/seedu/address/model/service/Service.java
Labels: type.Feature

#47 Storage update v1
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entity/shop/Shop.java
  src/main/java/seedu/address/model/service/Part.java
  src/main/java/seedu/address/model/service/Vehicle.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCustomer.java
  src/main/java/seedu/address/storage/JsonAdaptedVehicle.java
  src/main/java/seedu/address/storage/JsonSerializableShop.java
  src/main/java/seedu/address/storage/JsonShopStorage.java
  src/main/java/seedu/address/storage/ShopStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.MEDIUM

#48 Update storage v1.1
  src/main/java/seedu/address/model/ReadOnlyShop.java
  src/main/java/seedu/address/model/entity/shop/Shop.java
  src/main/java/seedu/address/model/service/Part.java
  src/main/java/seedu/address/model/service/PartMap.java
  src/main/java/seedu/address/model/service/PartType.java
  src/main/java/seedu/address/model/service/Service.java
  src/main/java/seedu/address/model/service/ServiceStatus.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPart.java
  src/main/java/seedu/address/storage/JsonAdaptedService.java
  src/main/java/seedu/address/storage/JsonSerializableShop.java
Labels: priority.MEDIUM

#52 Add undo and redo feature
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/AddPartCommand.java
  src/main/java/seedu/address/logic/commands/AddServiceCommand.java
  src/main/java/seedu/address/logic/commands/AddVehicleCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/RedoableCommand.java
  src/main/java/seedu/address/logic/commands/StackUndoRedo.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.LOW, type.DeveloperGuide, type.Documentation, type.Feature

#61 Remove Part class
  src/main/java/seedu/address/logic/commands/AddPartCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entity/shop/Shop.java
  src/main/java/seedu/address/model/service/Part.java
  src/main/java/seedu/address/model/service/PartMap.java
  src/main/java/seedu/address/model/service/Service.java
  src/main/java/seedu/address/model/service/exception/InsufficientPartException.java
  src/main/java/seedu/address/model/service/exception/PartNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPart.java
  src/main/java/seedu/address/storage/JsonAdaptedService.java
  src/main/java/seedu/address/storage/JsonSerializableShop.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.MEDIUM, type.Enhancement, type.Task

#73 List Customers & Vehicles
  .gitignore
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ListCustomersCommand.java
  src/main/java/seedu/address/logic/commands/ListVehiclesCommand.java
  src/main/java/seedu/address/logic/commands/ResultType.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entity/person/Customer.java
  src/main/java/seedu/address/model/mapping/CustomerVehicleMap.java
  src/main/java/seedu/address/model/mapping/VehicleDataMap.java
  src/main/java/seedu/address/model/service/PartType.java
  src/main/java/seedu/address/model/service/Vehicle.java
  src/main/java/seedu/address/model/service/VehicleType.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/CustomerCard.java
  src/main/java/seedu/address/ui/CustomerListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/VehicleCard.java
  src/main/java/seedu/address/ui/VehicleListPanel.java
  src/main/resources/view/CustomerListCard.fxml
  src/main/resources/view/CustomerListPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/VehicleListCard.fxml
  src/main/resources/view/VehicleListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.HIGH, type.Feature

#74 Add List Services Command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListServicesCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/mapping/ServiceDataMap.java
  src/main/java/seedu/address/model/service/PartMap.java
  src/main/java/seedu/address/model/service/Service.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ServiceCard.java
  src/main/java/seedu/address/ui/ServiceListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ServiceListCard.fxml
  src/main/resources/view/ServiceListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.HIGH, type.Feature

#76 Add commands gui integration
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/AddServiceCommand.java
  src/main/java/seedu/address/logic/commands/AddVehicleCommand.java
  src/main/java/seedu/address/logic/parser/AddVehicleCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/mapping/CustomerVehicleMap.java
  src/main/java/seedu/address/model/mapping/ServiceDataMap.java
  src/main/java/seedu/address/model/mapping/VehicleDataMap.java
  src/main/java/seedu/address/model/service/Service.java
  src/main/java/seedu/address/model/service/Vehicle.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonSerializableShop.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.HIGH, type.Feature

#78 View Customer & Vehicle
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ResultType.java
  src/main/java/seedu/address/logic/commands/ViewCustomerCommand.java
  src/main/java/seedu/address/logic/commands/ViewVehicleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewVehicleCommandParser.java
  src/main/java/seedu/address/model/entity/person/Person.java
Labels: priority.MEDIUM, type.Feature

#84 Updating DG
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/ViewSequenceDiagram.png
Labels: type.DeveloperGuide

#88 DG Updates
  docs/DeveloperGuide.md
  docs/diagrams/SetServicePrioritySequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/SetServicePrioritySequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.DeveloperGuide

#102 Minor dev guides and code improvement
  docs/DeveloperGuide.md
  docs/diagrams/UndoRedo7.puml
  docs/images/UndoRedo7.png
  src/main/java/seedu/address/logic/commands/StackUndoRedo.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
Labels: type.Documentation

#107 Add TotalAppointment command feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/TotalAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/TotalAppointmentCommandParser.java
  src/main/java/seedu/address/model/service/appointment/Appointment.java
Labels: type.Enhancement, type.Feature

#109 Julio doc changes
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#117 Update Userguide
  docs/UserGuide.md
Labels: type.Documentation
